#!/usr/bin/env python3
"""
codegen.py - Build-time code generator for KG static data.

Loads kg_config/ontology.json and kg_config/synonym_map.json, computes
transitive closure, priority ranking, and emits a C++ header with constexpr
arrays for FPGA/embedded deployment.
"""

import json
import os
import argparse
import sys


def load_json_file(path):
    """Load JSON file safely."""
    with open(path, "r", encoding="utf-8") as fh:
        return json.load(fh)


def load_configs(ontology_path, synonym_path):
    """Load ontology and synonym configs (graceful fallback)."""
    ontology_graph = {}
    synonym_map = {}

    if os.path.isfile(ontology_path):
        try:
            data = load_json_file(ontology_path)
            if isinstance(data, dict) and "ontology_graph" in data:
                og = data["ontology_graph"]
                if isinstance(og, dict):
                    ontology_graph = og
        except (json.JSONDecodeError, IOError):
            pass

    if os.path.isfile(synonym_path):
        try:
            sm = load_json_file(synonym_path)
            if isinstance(sm, dict):
                synonym_map = sm
        except (json.JSONDecodeError, IOError):
            pass

    return ontology_graph, synonym_map


def compute_closure(ontology_graph, synonym_map):
    """Compute transitive closure: token/alias -> [COCO classes]."""
    closure = {}

    # Add all canonical tokens (with validation)
    for token, classes in ontology_graph.items():
        if isinstance(classes, list) and all(isinstance(c, str) for c in classes):
            closure[token] = classes

    # Add all aliases (resolve to canonical)
    for alias, canonical in synonym_map.items():
        if isinstance(canonical, str) and canonical in closure:
            closure[alias] = closure[canonical]

    return closure


def compute_class_index_and_priorities(closure):
    """Build global COCO class index and compute priorities by frequency.
    
    Priority: classes appearing in more token lists get lower indices (higher priority).
    Tie-breaking: alphabetical order.
    """
    # Collect all unique classes
    all_classes = set()
    for classes in closure.values():
        all_classes.update(classes)

    if len(all_classes) > 255:
        raise ValueError(
            f"Too many COCO classes: {len(all_classes)} > 255 (uint8_t overflow)"
        )

    # Count frequency (co-occurrence count)
    frequency = {}
    for classes in closure.values():
        for c in classes:
            frequency[c] = frequency.get(c, 0) + 1

    # Sort by (frequency DESC, name ASC) — higher frequency gets lower index
    sorted_classes = sorted(all_classes, key=lambda c: (-frequency[c], c))

    # Build index map
    class_to_index = {c: i for i, c in enumerate(sorted_classes)}

    return sorted_classes, class_to_index


def reorder_classes_by_priority(closure, class_to_index):
    """For each token, reorder its classes by priority (their indices)."""
    reordered = {}
    for token, classes in closure.items():
        # Sort classes by their index (lower index = higher priority)
        sorted_classes = sorted(classes, key=lambda c: class_to_index[c])
        reordered[token] = sorted_classes
    return reordered


def make_token_name(token):
    """Convert token to valid C identifier (uppercase, alphanumeric + _)."""
    result = token.upper()
    result = "".join(c if c.isalnum() else "_" for c in result)
    # Ensure it doesn't start with a digit
    if result and result[0].isdigit():
        result = "_" + result
    return result


def generate_cpp_header(sorted_classes, closure, class_to_index, output_path):
    """Generate C++ header with constexpr arrays."""
    lines = []

    # Header comment
    lines.append("// AUTO-GENERATED by codegen.py — do not edit.")
    lines.append("// Re-run: python codegen.py")
    lines.append("")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("#include <stddef.h>")
    lines.append("")

    # NUM_COCO_CLASSES constant
    lines.append(f"constexpr uint8_t NUM_COCO_CLASSES = {len(sorted_classes)};")
    lines.append("")

    # COCO_CLASS_NAMES array for debug printing
    lines.append("constexpr const char* COCO_CLASS_NAMES[NUM_COCO_CLASSES] = {")
    for class_name in sorted_classes:
        lines.append(f'    "{class_name}",')
    lines.append("};")
    lines.append("")

    # Token class arrays (sorted by token name for consistency)
    for token in sorted(closure.keys()):
        classes = closure[token]
        c_name = make_token_name(token)
        indices = [class_to_index[c] for c in classes]
        indices_str = ", ".join(str(i) for i in indices)

        lines.append(f"constexpr uint8_t KG_{c_name}_CLASSES[] = {{ {indices_str} }};")
        lines.append(f"constexpr uint8_t KG_{c_name}_LEN = {len(classes)};")
        lines.append("")

    # Write to file
    header_content = "\n".join(lines)
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(header_content)


def main():
    parser = argparse.ArgumentParser(
        description="Generate C++ header from KG configs (build-time tool)"
    )
    parser.add_argument(
        "--ontology",
        help="Path to ontology.json",
        default="kg_config/ontology.json",
    )
    parser.add_argument(
        "--synonyms",
        help="Path to synonym_map.json",
        default="kg_config/synonym_map.json",
    )
    parser.add_argument(
        "--output",
        help="Output C++ header path",
        default="include/kg_data.h",
    )
    args = parser.parse_args()

    # Load configs
    ontology_graph, synonym_map = load_configs(args.ontology, args.synonyms)

    if not ontology_graph:
        print("ERROR: ontology_graph is empty. Check kg_config/ontology.json", file=sys.stderr)
        sys.exit(1)

    # Compute transitive closure
    closure = compute_closure(ontology_graph, synonym_map)

    if not closure:
        print("ERROR: closure is empty after validation", file=sys.stderr)
        sys.exit(1)

    # Build index and priorities
    sorted_classes, class_to_index = compute_class_index_and_priorities(closure)

    # Reorder classes by priority
    closure = reorder_classes_by_priority(closure, class_to_index)

    # Generate C++ header
    try:
        generate_cpp_header(sorted_classes, closure, class_to_index, args.output)
    except Exception as e:
        print(f"ERROR: Failed to generate header: {e}", file=sys.stderr)
        sys.exit(1)

    # Print summary
    print(f"✓ Generated {args.output}")
    print(f"  Tokens: {len(closure)}")
    print(f"  COCO classes: {len(sorted_classes)}")


if __name__ == "__main__":
    main()
