// AUTO-GENERATED by codegen.py — do not edit.
// Re-run: python codegen.py

#pragma once
#include <stdint.h>
#include <stddef.h>

constexpr uint8_t NUM_COCO_CLASSES = 76;

constexpr const char* COCO_CLASS_NAMES[NUM_COCO_CLASSES] = {
    "person",
    "cup",
    "phone",
    "bottle",
    "door",
    "book",
    "sandwich",
    "bag",
    "glass",
    "water bottle",
    "wine glass",
    "box",
    "camera",
    "dog",
    "fork",
    "kettle",
    "mug",
    "window",
    "apple",
    "banana",
    "cat",
    "chair",
    "chips",
    "cookie",
    "leash",
    "microphone",
    "napkin",
    "orange",
    "pizza",
    "plate",
    "ball",
    "button",
    "car",
    "cart",
    "container",
    "drawer",
    "frisbee",
    "glasses",
    "handle",
    "keyboard",
    "laptop",
    "road",
    "backpack",
    "bat",
    "bed",
    "belt",
    "bench",
    "bicycle",
    "broom",
    "bucket",
    "couch",
    "desk",
    "eye",
    "face",
    "hand",
    "hat",
    "helmet",
    "knife",
    "mop",
    "motorcycle",
    "mouse",
    "oven",
    "pan",
    "pants",
    "pot",
    "racket",
    "shirt",
    "shoe",
    "shoes",
    "sidewalk",
    "soap",
    "sofa",
    "sports",
    "steering wheel",
    "stove",
    "street",
};

constexpr uint8_t KG_BARK_CLASSES[] = { 0, 13, 20, 24 };
constexpr uint8_t KG_BARK_LEN = 4;

constexpr uint8_t KG_CAPTURE_CLASSES[] = { 0, 2, 12 };
constexpr uint8_t KG_CAPTURE_LEN = 3;

constexpr uint8_t KG_CHUG_CLASSES[] = { 1, 3, 8, 9, 10 };
constexpr uint8_t KG_CHUG_LEN = 5;

constexpr uint8_t KG_CHUGGED_CLASSES[] = { 1, 3, 8, 9, 10 };
constexpr uint8_t KG_CHUGGED_LEN = 5;

constexpr uint8_t KG_CLEAN_CLASSES[] = { 48, 49, 58, 70 };
constexpr uint8_t KG_CLEAN_LEN = 4;

constexpr uint8_t KG_CLOSE_CLASSES[] = { 4, 11, 17 };
constexpr uint8_t KG_CLOSE_LEN = 3;

constexpr uint8_t KG_COFFEE_CLASSES[] = { 1, 15, 16 };
constexpr uint8_t KG_COFFEE_LEN = 3;

constexpr uint8_t KG_CONSUME_CLASSES[] = { 6, 14, 18, 19, 27, 28, 29 };
constexpr uint8_t KG_CONSUME_LEN = 7;

constexpr uint8_t KG_CONSUMING_CLASSES[] = { 6, 14, 18, 19, 27, 28, 29 };
constexpr uint8_t KG_CONSUMING_LEN = 7;

constexpr uint8_t KG_COOK_CLASSES[] = { 14, 57, 61, 62, 64, 74 };
constexpr uint8_t KG_COOK_LEN = 6;

constexpr uint8_t KG_DRINK_CLASSES[] = { 1, 3, 8, 9, 10 };
constexpr uint8_t KG_DRINK_LEN = 5;

constexpr uint8_t KG_DRINK_HOT_CLASSES[] = { 1, 15, 16 };
constexpr uint8_t KG_DRINK_HOT_LEN = 3;

constexpr uint8_t KG_DRIVE_CLASSES[] = { 0, 32, 41, 73 };
constexpr uint8_t KG_DRIVE_LEN = 4;

constexpr uint8_t KG_EAT_CLASSES[] = { 6, 14, 18, 19, 27, 28, 29 };
constexpr uint8_t KG_EAT_LEN = 7;

constexpr uint8_t KG_EAT_SNACK_CLASSES[] = { 6, 22, 23, 26 };
constexpr uint8_t KG_EAT_SNACK_LEN = 4;

constexpr uint8_t KG_FETCH_CLASSES[] = { 0, 1, 2, 3, 5, 7 };
constexpr uint8_t KG_FETCH_LEN = 6;

constexpr uint8_t KG_GRAB_CLASSES[] = { 0, 1, 2, 3, 5, 7 };
constexpr uint8_t KG_GRAB_LEN = 6;

constexpr uint8_t KG_HOLD_CLASSES[] = { 0, 1, 2, 3, 5, 7 };
constexpr uint8_t KG_HOLD_LEN = 6;

constexpr uint8_t KG_LOOK_CLASSES[] = { 0, 12, 52, 53 };
constexpr uint8_t KG_LOOK_LEN = 4;

constexpr uint8_t KG_OPEN_CLASSES[] = { 4, 11, 17, 34 };
constexpr uint8_t KG_OPEN_LEN = 4;

constexpr uint8_t KG_OPENUP_CLASSES[] = { 4, 11, 17, 34 };
constexpr uint8_t KG_OPENUP_LEN = 4;

constexpr uint8_t KG_PET_CLASSES[] = { 0, 13, 20, 24 };
constexpr uint8_t KG_PET_LEN = 4;

constexpr uint8_t KG_PETTING_CLASSES[] = { 0, 13, 20, 24 };
constexpr uint8_t KG_PETTING_LEN = 4;

constexpr uint8_t KG_PHOTO_CLASSES[] = { 0, 2, 12 };
constexpr uint8_t KG_PHOTO_LEN = 3;

constexpr uint8_t KG_PICK_CLASSES[] = { 0, 1, 2, 3, 5, 7 };
constexpr uint8_t KG_PICK_LEN = 6;

constexpr uint8_t KG_PICK_UP_CLASSES[] = { 0, 1, 2, 3, 5, 7 };
constexpr uint8_t KG_PICK_UP_LEN = 6;

constexpr uint8_t KG_PLAY_CLASSES[] = { 0, 30, 36, 43, 65, 72 };
constexpr uint8_t KG_PLAY_LEN = 6;

constexpr uint8_t KG_PULL_CLASSES[] = { 4, 35, 38 };
constexpr uint8_t KG_PULL_LEN = 3;

constexpr uint8_t KG_PULLED_CLASSES[] = { 4, 35, 38 };
constexpr uint8_t KG_PULLED_LEN = 3;

constexpr uint8_t KG_PUSH_CLASSES[] = { 4, 31, 33 };
constexpr uint8_t KG_PUSH_LEN = 3;

constexpr uint8_t KG_PUSHES_CLASSES[] = { 4, 31, 33 };
constexpr uint8_t KG_PUSHES_LEN = 3;

constexpr uint8_t KG_READ_CLASSES[] = { 0, 5, 21, 37, 39, 40 };
constexpr uint8_t KG_READ_LEN = 6;

constexpr uint8_t KG_RIDE_CLASSES[] = { 0, 32, 47, 56, 59 };
constexpr uint8_t KG_RIDE_LEN = 5;

constexpr uint8_t KG_SHUT_CLASSES[] = { 4, 11, 17 };
constexpr uint8_t KG_SHUT_LEN = 3;

constexpr uint8_t KG_SIP_CLASSES[] = { 1, 3, 8, 9, 10 };
constexpr uint8_t KG_SIP_LEN = 5;

constexpr uint8_t KG_SIP_HOT_CLASSES[] = { 1, 15, 16 };
constexpr uint8_t KG_SIP_HOT_LEN = 3;

constexpr uint8_t KG_SIPS_CLASSES[] = { 1, 3, 8, 9, 10 };
constexpr uint8_t KG_SIPS_LEN = 5;

constexpr uint8_t KG_SIT_CLASSES[] = { 0, 21, 44, 46, 50, 71 };
constexpr uint8_t KG_SIT_LEN = 6;

constexpr uint8_t KG_SNACK_CLASSES[] = { 6, 22, 23, 26 };
constexpr uint8_t KG_SNACK_LEN = 4;

constexpr uint8_t KG_SNACKING_CLASSES[] = { 6, 22, 23, 26 };
constexpr uint8_t KG_SNACKING_LEN = 4;

constexpr uint8_t KG_SPEAK_CLASSES[] = { 0, 2, 25 };
constexpr uint8_t KG_SPEAK_LEN = 3;

constexpr uint8_t KG_TAKE_PHOTO_CLASSES[] = { 0, 2, 12 };
constexpr uint8_t KG_TAKE_PHOTO_LEN = 3;

constexpr uint8_t KG_TALK_CLASSES[] = { 0, 2, 25 };
constexpr uint8_t KG_TALK_LEN = 3;

constexpr uint8_t KG_TALKING_CLASSES[] = { 0, 2, 25 };
constexpr uint8_t KG_TALKING_LEN = 3;

constexpr uint8_t KG_TEA_CLASSES[] = { 1, 15, 16 };
constexpr uint8_t KG_TEA_LEN = 3;

constexpr uint8_t KG_THROW_CLASSES[] = { 0, 30, 36, 54 };
constexpr uint8_t KG_THROW_LEN = 4;

constexpr uint8_t KG_WALK_CLASSES[] = { 0, 13, 41, 67, 69, 75 };
constexpr uint8_t KG_WALK_LEN = 6;

constexpr uint8_t KG_WEAR_CLASSES[] = { 37, 42, 45, 55, 63, 66, 68 };
constexpr uint8_t KG_WEAR_LEN = 7;

constexpr uint8_t KG_WORK_CLASSES[] = { 0, 21, 39, 40, 51, 60 };
constexpr uint8_t KG_WORK_LEN = 6;
